spring:
  application:
    name: SERVICE-DEPOSIT-TRANSFERT-WITHDRAW
  datasource:
    url: jdbc:mysql://dtw-db:3306/dtw_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    exchange: banking_events
    queue: dtw_queue
    routing-key: dtw.#

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
    hostname: service-deposit-transfert-withdraw
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

server:
  port: 8001
  servlet:
    context-path: /api/v1/dtw

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.banking.dtw: DEBUG
    org.hibernate: INFO
