server:
  port: 8001
  address: 0.0.0.0

spring:
  application:
    name: service-depot-transfert-withdraw

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

app:
  name: service-depot-transfert-withdraw
  env: local
  debug: true

db:
  connection: mysql
  host: localhost
  port: 3306
  database: banking_system
  username: root
  password: root

rabbitmq:
  host: localhost
  port: 5672
  user: guest
  password: guest
  vhost: /
  queue: default
  exchange:
    name: deposit_transfer_withdraw_events
    type: fanout

sanctum:
  stateful:
    - "localhost:8081"
    - "localhost:80"

logging:
  level: debug
