server:
  port: 8001
  address: 0.0.0.0

spring:
  application:
    name: service-depot-transfert-withdraw

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

app:
  name: service-depot-transfert-withdraw
  env: local
  debug: true

db:
  driver: mysql
  host: localhost          # Matches the Docker service name
  port: 3306
  database: banking_dtw
  username: root
  password: 
  charset: utf8mb4
  collation: utf8mb4_unicode_ci

rabbitmq:
  host: rabbitmq
  port: 5672
  user: guest
  password: guest
  vhost: /
  queue: default
  exchange:
    name: deposit_transfer_withdraw_events
    type: fanout

sanctum:
  stateful:
    - "localhost:8081"
    - "localhost:80"

logging:
  level: debug
